version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default

    steps:
      - checkout
      - run:
          name: Setup Miniconda
          command: |
            wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Activate
          command: |
            CONDA_BASE=$($HOME/miniconda/bin/conda info --base)
            source $CONDA_PREFIX/etc/profile.d/conda.sh
            $HOME/miniconda/bin/conda activate base
      - run:
          name: Init
          command: |
            $HOME/miniconda/bin/conda init --all
      - run:
          name: Update
          command: |
            $HOME/miniconda/bin/conda update conda
      - run:
          name: Install Dependencies
          command: |
            $HOME/miniconda/bin/conda install -c conda-forge conda-merge
            $HOME/miniconda/bin/conda merge env.common.yml env.cpu.yml > env.yml
            conda env create -f env.yml
      - run:
          name: Install
          command: |
            conda activate ocp-models
            pip install -e .
      - run:
          name: Test
          command: |
            pytest

workflows:
  main:
    jobs:
      - build-and-test
