version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: << parameters.executor >>
    parameters:
      executor:
        default: miniconda3
        description: conda executor
        type: executor

    steps:
      - checkout
      - run:
          command: |
            pip install conda-merge
            conda-merge env.common.yml env.cpu.yml > env.yml
            conda env create -f env.yml
            conda activate ocp-models
          name: Install Dependencies
      - run:
          command: |
            pip install -e .
            pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
