version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps
      - run:
          name: Setup Miniconda
          command: |
            if [ ! -d "$HOME/miniconda" ]; then
              wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              source ~/.bashrc
              $HOME/miniconda/bin/conda install -c conda-forge conda-merge
              $HOME/miniconda/bin/conda merge env.common.yml env.cpu.yml > env.yml
              $HOME/miniconda/bin/conda env create -f env.yml
            else
              source ~/.bashrc
              $HOME/miniconda/bin/conda env update -f env.yml --prune
            fi
      - save_cache:
          paths:
            - /home/circleci/miniconda
          key: deps
      - run:
          name: Install
          command: |
            $HOME/miniconda/bin/conda init --all
            $HOME/miniconda/bin/conda activate ocp-models
            pip install -e .
      - run:
          name: Test
          command: |
            pytest

workflows:
  main:
    jobs:
      - build-and-test
