version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            pip install conda-merge
            conda-merge env.common.yml env.cpu.yml > env.yml
            conda env create -f env.yml
            conda activate ocp-models
          name: Install Dependencies
      - python/save-cache
      - run:
          command: |
            pip install -e .
            pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
